---
repos:
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v1.6.0'  # Use the sha / tag you want to point at
    hooks:
      - id: autopep8
  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args:
          - --exclude=tests/*
          - --max-complexity=30
          - --show-source
          - --statistics
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        exclude: ^(tests/)
        args:
          - --source
          - --explain
          - --convention=google
        additional_dependencies: ["toml"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.37.2
    hooks:
      - id: pyupgrade
        # TODO: remove `--keep-runtime-typing` option
        args: ["--py37-plus", "--keep-runtime-typing"]
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: pyright
        language: node
        pass_filenames: false
        types: [python]
        additional_dependencies: ["pyright"]
        args:
          - --project=pyproject.toml
