x-app: &default-app
  build:
    context: "."
    target: "app"
    args:
      - "FLASK_DEBUG=${FLASK_DEBUG:-false}"
  env_file:
    - ".env"
  restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
  stop_grace_period: "3s"
  tty: true
  volumes:
    - "${DOCKER_WEB_VOLUME:-./public:/app/public}"
  depends_on:
    - "mongodb"

services:
  mongodb:
    image: mongo:latest
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    env_file:
      - ".env"
    environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    deploy:
      resources:
        limits:
          cpus: "${DOCKER_MONGODB_CPUS:-0}"
          memory: "${DOCKER_MONGODB_MEMORY:-0}"
    networks:
      - default

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.2
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    env_file:
      - ".env"
    ports:
      - 9200:9200
    volumes:
      - es:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          cpus: "${DOCKER_ELASTICSEARCH_CPUS:-0}"
          memory: "${DOCKER_ELASTICSEARCH_MEMORY:-0}"
    networks:
      - default

  kibana:
    image: docker.elastic.co/kibana/kibana:8.3.2
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    env_file:
      - ".env"
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    deploy:
      resources:
        limits:
          cpus: "${DOCKER_KIBANA_CPUS:-0}"
          memory: "${DOCKER_KIBANA_MEMORY:-0}"
    networks:
      - default

  web:
    <<: *default-app
    hostname: gator_api
    deploy:
      resources:
        limits:
          cpus: "${DOCKER_WEB_CPUS:-0}"
          memory: "${DOCKER_WEB_MEMORY:-0}"
    healthcheck:
      test: "${DOCKER_WEB_HEALTHCHECK_TEST:-curl localhost:5000/ping}"
      interval: "60s"
      timeout: "3s"
      start_period: "5s"
      retries: 3
    ports:
      - "${DOCKER_WEB_PORT_FORWARD:-127.0.0.1:5000}:5000"
    links:
      - mongodb
    networks:
      - default
    depends_on:
      - mongodb
      - elasticsearch
      - kibana

volumes:
  mongodb: {}
  es: {}

networks:
  default:
    name: sqrl_network
    external: true
